### ISSUE TITLE
bloop block when start

### ISSUE THREAD

**Issue by 982945902** [BloopAI/bloop#1054] opened 2023-10-17 02:55 UTC
**Describe the bug**
when i start bloop that block like this:
![image](https://github.com/BloopAI/bloop/assets/49055103/1dcd69c4-86d0-4215-b283-08c21e0e7d55)

**Expected behavior**
What did you expect to happen?

**To Reproduce**
How can we reproduce the bug? Helpful information could include:
- Details about your system
- The data that you had indexed
- The query that you ran

**Screenshots or output**
If applicable, add screenshots to help illustrate the bug.

**Additional context**

**Comment by itp18506** [comment] 2023-10-17 23:02
Same issue to me after a sudden crash and disappear in Ubuntu 22.04

**Comment by ggordonhall** [comment] 2023-10-24 16:16
This is a duplicate of https://github.com/BloopAI/bloop/issues/1035

Can you post the contents of your log file in that thread to help pin this down?

**Closed by ggordonhall** 2023-10-24 16:16 UTC
Labels: bug
