### ISSUE TITLE
MacOs 10.14.1  can not open this app

### ISSUE THREAD

**Issue by brizer** [BloopAI/bloop#800] opened 2023-08-02 05:36 UTC
**Describe the bug**
MacOs 10.14.1  can not open this app

**Expected behavior**
What did you expect to happen?

**To Reproduce**
How can we reproduce the bug? Helpful information could include:
- Details about your system
- The data that you had indexed
- The query that you ran

**Screenshots or output**
If applicable, add screenshots to help illustrate the bug.

**Additional context**

**Comment by brizer** [comment] 2023-08-02 05:37
...

**Comment by ggordonhall** [comment] 2023-08-02 17:18
Do you experience the same behaviour as https://github.com/BloopAI/bloop/issues/715?

**Comment by brizer** [comment] 2023-08-03 01:07
yes, yes.

**Comment by ggordonhall** [comment] 2023-08-03 07:03
Closing as duplicate of https://github.com/BloopAI/bloop/issues/715

**Closed by ggordonhall** 2023-08-03 07:03 UTC
Labels: bug
