### ISSUE TITLE
I can't log into the bloop.ai client via github

### ISSUE THREAD

**Issue by the6thexe** [BloopAI/bloop#1288] opened 2024-08-22 12:47 UTC
### Discussed in https://github.com/BloopAI/bloop/discussions/1287

<div type='discussions-op-text'>

<sup>Originally posted by **the6thexe** August 22, 2024</sup>
When I click "Guthub auth" I can't connect to the authorization site
The link doesn't work either
![image](https://github.com/user-attachments/assets/d6de5261-5e7f-4240-8020-d66243aa7ea0)

[tr]
Can't access the siteCheck the hostname production-github-oauth.auth.eu-west-1.amazoncognito.com for typos.
If everything is correct, use the Windows Network Diagnostics tool.
DNS_PROBE_FINISHED_NXDOMAIN</div>

**Comment by banduoba** [comment] 2024-08-22 16:33
Me too

**Comment by banduoba** [comment] 2024-08-22 16:33
This is a bug

**Comment by stunningpixels** [comment] 2024-08-27 11:08
Duplicate of https://github.com/BloopAI/bloop/issues/1286

**Closed as completed by stunningpixels** 2024-08-27 11:08 UTC
