### ISSUE TITLE
#v0.4.17，#win10，can not get into the application

### ISSUE THREAD

**Issue by Haoyu2405** [BloopAI/bloop#939] opened 2023-09-10 16:03 UTC
# In the Windows 10 system, when I double-click on the icon and stay on this interface.
# What should I do to solve this problem?
![image](https://github.com/BloopAI/bloop/assets/84794739/6c251826-1c09-45fc-9166-3be9985ae2e1)

**Comment by Haoyu2405** [comment] 2023-09-10 16:06
I tried uninstalling and reinstalling, but it still didn't work.

**Comment by CAN1177** [comment] 2023-09-12 06:03
#v0.4.17，#mac intel，I also encountered this problem

**Comment by ggordonhall** [comment] 2023-09-12 11:47
Closing this as it is a duplicate of https://github.com/BloopAI/bloop/issues/917

**Closed by ggordonhall** 2023-09-12 11:47 UTC
