### ISSUE TITLE
0.4.7 not starting in MacOS Ventura 13.2.1 (Apple Silicon)

### ISSUE THREAD

**Issue by ObaidUr-Rahmaan** [BloopAI/bloop#715] opened 2023-07-02 00:26 UTC
**Describe the bug**
App bounces forever and doesn't actually startup, when clicked.

**Expected behavior**
When opening the App, it should just open.

**To Reproduce**
How can we reproduce the bug? Helpful information could include:
- Download `bloop_0.4.7_aarch64.dmg` on MacOS Ventura 13.2.1
- Try to start the App

**Screenshots or output**
N/A - Description is sufficient

**Additional context**
I've tried to do a complete uninstall and delete caches; still the same behaviour...

**Comment by ObaidUr-Rahmaan** [comment] 2023-07-02 00:35
Okay I tried installing every other version in descending order (0.4.6, 0.4.5...) until 0.3.5. I found the work-around ✅

Solution:

1) Install 0.3.5 - https://github.com/BloopAI/bloop/releases/tag/v0.3.5
2) App will now open
3) App will prompt to update to latest version
4) Now you can open the App

This works for me. I'll leave admin/s to decide whether to keep this report open 🙏🏼

**Comment by CheinTian** [comment] 2023-07-03 04:52
Thanks for the solution, works for me

**Comment by ggordonhall** [comment] 2023-07-03 08:26
@CheinTian Which version of MacOS are you running? I can't reproduce this on MacOS Ventura 13.4.1

**Comment by CheinTian** [comment] 2023-07-03 08:43
> 

Ventura 13.4.1 (Apple Silicon)

This is my scenario:

First, Install 0.4.6.
Then, Install 0.4.7. 
Finally, bloop can't start(not responsing)

**Comment by ggordonhall** [comment] 2023-07-03 10:29
@CheinTian Did you install 0.4.7 via the update popup, or did you download it from the releases page? Also did you have any repos indexed when updating from 0.4.6 to 0.4.7?

**Comment by CheinTian** [comment] 2023-07-04 09:30
> @CheinTian Did you install 0.4.7 via the update popup, or did you download it from the releases page? Also did you have any repos indexed when updating from 0.4.6 to 0.4.7?

One local repository (very large repo about 3GB) indexed before uprade to 0.4.7 by downloading the dmg.

Maybe caused by the large repo, after i remove it, i can not reproduce the problem.

**Comment by ObaidUr-Rahmaan** [comment] 2023-07-04 18:57
I should probably note that, for me, there were also 2 repos already indexed before I encountered the problem. I'm not sure if that could've been a potential cause for the glitchy behaviour on startup 🤷🏼

**Comment by will-gant** [comment] 2023-07-05 09:58
I've been hitting the same issue with `bloop_0.4.7_aarch64.dmg` (and numerous other recent releases), while running macOS Ventura version 13.1 (22C65). In each case I downloaded the binary from the releases page in this repo.

I had previously used earlier versions of the application without issue, and had indexed a number of repos. Like @ObaidUr-Rahmaan, deleting the binary, clearing the caches, etc did nothing. And I've likewise found that installing 0.3.5 and auto-updating from there seems to work.

**Comment by ggordonhall** [comment] 2023-07-06 22:02
Thanks for the reports, we're investigating this. 

Does deleting `~/Library/Application\ Support/ai.bloop.bloop` work? We've moved some of our permanent state there and there may be an issue with migrations. I'm updating our documentation to make this clear.

**Comment by ObaidUr-Rahmaan** [comment] 2023-07-07 15:55
I'm not sure about others, but I can't reproduce this problem anymore. Thankfully!

To verify, today I uninstalled bloop, rm -rf'd cache folder. And then reinstalled 0.4.7 on MacOS Ventura 13.3 (Apple Silicon). No issues now. The install works fine and the App opens.  

Unless anyone can reproduce this. I think this bug report is okay to close?

**Comment by joyvuu-dave** [comment] 2023-07-07 16:33
Well, for me it did work the first time I ran it and I only encountered the bug after indexing some repos, closing the app, and attempting to open later on. So I imagine there is indeed a issue that needs to be addressed and it wasn't something specific to your system @ObaidUr-Rahmaan.

**Comment by kloudtaxi** [comment] 2023-07-31 15:15
I was able to resolve the issue by upgrading the MacOS to the latest public release Ventura `Version 13.5 (22G74)`

**Additional Notes**
- This issue is not limited to Apple silicon, I experienced the same on Intel as well. 
- @ggordonhall I tried deleting `~/Library/Application\ Support/ai.bloop.bloop ` but it did not help

**Comment by brizer** [comment] 2023-08-03 09:01
It's it fixed?

**Comment by ggordonhall** [comment] 2023-08-28 09:15
We fixed an issue with DB migrations that caused this behaviour: https://github.com/BloopAI/bloop/pull/841. It may be possible to trigger in other ways, so keeping this open for now.

**Closed** 2023-09-20 17:46 UTC
Labels: bug

**Comment by brizer** [comment] 2023-09-21 09:55
Fixed it?
