### ISSUE TITLE
Light mode?

### ISSUE THREAD

**Issue by p0358** [BloopAI/bloop#310] opened 2023-03-22 11:59 UTC
**What's the problem?**
I'm not sure what kind of eyes or monitors y'all have, but I find this dark mode of this app absolutely unreadable. It's dark gray text on dark background and it's basically impossible for me to read anything on this. No other apps with dark mode are that bad, but this one is 100% impossible to use because of that.

**What's the solution?**
Just add light mode :/ But also even in dark mode, the buttons for "Discord" or "Report a bug" are fine/reasonable, but most of the text is unreadable.

**Additional context**
Dark modes overall are pretty bad for many people with astigmatism.
* https://medium.com/@h_locke/why-dark-mode-causes-more-accessibility-issues-than-it-solves-d2f8359bb46a
* https://kevq.uk/is-dark-mode-such-a-good-idea/

**Comment by p0358** [comment] 2023-03-22 12:20
btw the opacity in this window also doesn't really help xd
![image](https://user-images.githubusercontent.com/5182588/226902995-7df724fa-8a05-457e-91af-f13e1cc4008a.png)

**Comment by karthiknadar1204** [comment] 2023-03-22 15:29
i would like to work on this issue,please assign it to me

**Comment by p0358** [comment] 2023-03-23 10:42
Well the dark gray text for me is barely readable in regular daylight in a room, I could only read it when putting down window blinders or looking at the screen from the side, irregardless of whether the screen is matte or not. Perhaps that's a matter of having a TN screen rather than IPS or OLED, but I think design should take this into consideration, because I didn't really encounter something like that to this level in any other app that I recall (though I'd still prefer to just use light mode instead personally xd)

> The text in the bottom left is a little dim, but it's background info anyway.

You could say that, but the same color is used for tabs on the left and description under "No repositories", and I think those don't apply to that category. Similar with icons and text on the top, there's barely any contrast on them

**Comment by ISHUMICHEAL2020** [comment] 2023-03-25 07:11
FIX IT EASILY

**Comment by jespertheend** [comment] 2023-04-01 13:58
Best way to demonstrate the issue is with an actual unedited photo:

![2D0AF178-0E7E-423A-A187-23B3D2FC94C9](https://user-images.githubusercontent.com/2737650/229293023-9090cf9d-93a1-41b6-9ba5-aa6aa90dc4d1.jpeg)

Light mode would fix this, but if that's too much work changing the contrast of some of the UI would work as well.
Much of the UI does not pass [AA WebAIM guidelines](https://web.dev/color-and-contrast-accessibility/?utm_source=devtools):
![image](https://user-images.githubusercontent.com/2737650/229293500-9f591668-b698-4311-8493-a3381b5c1c80.png)

**Comment by stunningpixels** [comment] 2023-04-12 11:42
Thanks for flagging - we're looking at options

**Comment by ggordonhall** [comment] 2023-06-07 09:30
Themes (including light mode) are supported as of v0.4.0! https://github.com/BloopAI/bloop/releases/tag/v0.4.3

**Closed by ggordonhall** 2023-06-07 09:30 UTC
Labels: enhancement
